import { nodeIdToNoteName } from "./graph-paths"
import type { AstNode, AstEdge, CommunityMap } from "./types"

export function renderNodeNote(args: {
  node: AstNode
  community: number
  outgoing: AstEdge[]
  incoming: AstEdge[]
  nodeIndex: Map<string, AstNode>
  graphDir: string
}): string {
  const { node, community, outgoing, incoming, nodeIndex, graphDir } = args

  function noteLink(targetId: string): string {
    const target = nodeIndex.get(targetId)
    const name = target?.name ?? targetId.split("#")[1] ?? targetId
    const noteName = nodeIdToNoteName(targetId, graphDir)
    const slug = noteName.replace(/^[^/]+\//, "").replace(/\.md$/, "")
    return `[[${slug}|${name}]]`
  }

  const frontmatter = [
    "---",
    `type: ${node.kind}`,
    `name: "${node.name}"`,
    `source_file: ${node.file}`,
    `line: ${node.line}`,
    `language: ${node.language}`,
    `community: ${community}`,
    `opengem_node: true`,
    "---",
  ].join("\n")

  const lines: string[] = [frontmatter, "", `# ${node.name}`, ""]

  if (node.docComment) {
    lines.push(`> ${node.docComment}`, "")
  }

  lines.push(`**File:** \`${node.file}\` · line ${node.line}  `)
  lines.push(`**Type:** ${node.kind} · **Community:** ${community}`, "")

  // Group outgoing edges by kind
  const outByKind = new Map<string, AstEdge[]>()
  for (const e of outgoing) {
    if (e.target.startsWith("__unresolved__")) continue
    const list = outByKind.get(e.kind) ?? []
    list.push(e)
    outByKind.set(e.kind, list)
  }

  for (const [kind, edgeList] of outByKind) {
    const label = kind.charAt(0).toUpperCase() + kind.slice(1)
    lines.push(`## ${label}`)
    for (const e of edgeList) {
      lines.push(`- ${noteLink(e.target)}`)
    }
    lines.push("")
  }

  // Incoming edges
  const incomingResolved = incoming.filter(e => !e.target.startsWith("__unresolved__"))
  if (incomingResolved.length > 0) {
    lines.push("## Referenced by")
    for (const e of incomingResolved) {
      lines.push(`- ${noteLink(e.source)}`)
    }
    lines.push("")
  }

  return lines.join("\n")
}

export function renderGraphIndex(graphDir: string, nodeCount: number, communities: number, indexedAt: string): string {
  return [
    "---",
    "opengem_graph_index: true",
    "---",
    "",
    "# Code Graph Index",
    "",
    `> Generated by OpenGem on ${indexedAt}`,
    `> ${nodeCount} nodes · ${communities} communities`,
    "",
    "Browse the graph in Obsidian's Graph View — filter by \`opengem_node: true\`.",
  ].join("\n") + "\n"
}
