#!/usr/bin/env node
import * as p from "@clack/prompts"
import { spawnSync } from "node:child_process"
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { homedir } from "node:os"
import { dirname, join, resolve } from "node:path"

// ── Obsidian CLI helpers ──────────────────────────────────────────────────────

function obsidian(args: string[]) {
  const r = spawnSync("obsidian", args, { encoding: "utf8" })
  return { exitCode: r.status ?? 1, stdout: r.stdout ?? "", stderr: r.stderr ?? "" }
}

function cliVersion(): string | null {
  const r = obsidian(["--version"])
  if (r.exitCode !== 0) return null
  return r.stdout.trim().split("\n")[0]?.trim() ?? null
}

function appRunning(): boolean {
  return obsidian(["vault"]).exitCode === 0
}

function activeVault(): string | null {
  const r = obsidian(["vault"])
  if (r.exitCode !== 0) return null
  const line = r.stdout.trim().split("\n").find(l => l.startsWith("name"))
  return line ? line.split(/\s+/).slice(1).join(" ").trim() : null
}

function listVaults(): string[] {
  const r = obsidian(["vaults"])
  if (r.exitCode !== 0) return []
  return r.stdout
    .trim()
    .split("\n")
    .filter(Boolean)
    .map(line => line.split("\t")[0].trim())
    .filter(Boolean)
}

// ── Wiki init helpers ─────────────────────────────────────────────────────────

const SCHEMA_MD = `# Wiki Schema

## Page conventions

Every wiki page should follow this structure:

\`\`\`
---
tags: [topic, subtopic]
source: [[raw/original-source]]
updated: YYYY-MM-DD
---

# Title

One paragraph summary.

## Key points
- ...

## Details
...

## See also
- [[related-page]]
\`\`\`

## Folder structure

- \`raw/\`    — original sources, never edited
- \`wiki/\`   — curated pages, one concept per file
- \`schema/\` — this file and other conventions
`

const INDEX_MD = `# Wiki Index

> generated by OpenGem — update with obsidian_wiki_refresh_index

`

function buildLogEntry() {
  const now = new Date().toISOString().replace("T", " ").slice(0, 16)
  return `# Wiki Log\n\n## ${now} — init\n- Wiki structure initialized by OpenGem\n`
}

function escapeContent(content: string): string {
  return content.replace(/\n/g, "\\n").replace(/\t/g, "\\t")
}

function createWikiFile(name: string, content: string, vault: string): boolean {
  const r = obsidian(["create", `name=${name}`, `content=${escapeContent(content)}`, `vault=${vault}`])
  return r.exitCode === 0
}

// ── Config helpers ────────────────────────────────────────────────────────────

function readConfig(configPath: string): Record<string, unknown> {
  if (!existsSync(configPath)) return {}
  try { return JSON.parse(readFileSync(configPath, "utf8")) } catch { return {} }
}

function saveConfig(configPath: string, vault: string) {
  const config = readConfig(configPath)
  const plugins = (config.plugin as unknown[][] | undefined) ?? []
  const filtered = plugins.filter(entry => {
    const name = Array.isArray(entry) ? entry[0] : entry
    return name !== "@cubocompany/opengem"
  })
  filtered.push(["@cubocompany/opengem", { defaultVault: vault }])
  config.plugin = filtered
  const dir = dirname(configPath)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n", "utf8")
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log()
  p.intro("OpenGem Setup")

  const s = p.spinner()

  // 1. Check CLI
  s.start("Checking Obsidian CLI...")
  const version = cliVersion()
  if (!version) {
    s.stop("Obsidian CLI not found")
    p.note(
      "Download and install the Obsidian CLI from https://obsidian.md/cli\nThen make sure `obsidian --version` works in your terminal.",
      "Missing requirement"
    )
    p.outro("Setup incomplete. Run `npx @cubocompany/opengem init` again after installing the CLI.")
    process.exit(1)
  }
  s.stop(`Obsidian CLI found (${version})`)

  // 2. Check app
  s.start("Checking Obsidian app...")
  if (!appRunning()) {
    s.stop("Obsidian app is not running")
    p.note("Open Obsidian and make sure at least one vault is loaded.", "Missing requirement")
    p.outro("Setup incomplete. Run `npx @cubocompany/opengem init` again after opening Obsidian.")
    process.exit(1)
  }
  s.stop("Obsidian app is running")

  // 3. Pick vault
  const active = activeVault()
  const all = listVaults()

  if (all.length === 0 && !active) {
    p.outro("No vaults found. Open a vault in Obsidian and run init again.")
    process.exit(1)
  }

  const vaultOptions = [
    ...all.map(v => ({
      value: v,
      label: v === active ? `${v}  (active)` : v,
    })),
    { value: "__manual__", label: "Enter manually" },
  ]

  const vaultChoice = await p.select({
    message: "Which vault do you want to use?",
    options: vaultOptions,
    initialValue: active ?? all[0],
  })
  if (p.isCancel(vaultChoice)) { p.cancel("Setup cancelled."); process.exit(0) }

  let vault: string
  if (vaultChoice === "__manual__") {
    const manual = await p.text({ message: "Vault name:", placeholder: "My Vault" })
    if (p.isCancel(manual)) { p.cancel("Setup cancelled."); process.exit(0) }
    vault = manual as string
  } else {
    vault = vaultChoice as string
  }

  // 4. Pick config location
  const globalPath = join(homedir(), ".opencode", "opencode.json")
  const localPath = resolve("opencode.json")

  const configChoice = await p.select({
    message: "Save config to:",
    options: [
      { value: "global", label: "Global", hint: `~/.opencode/opencode.json — works in any project` },
      { value: "local", label: "This project", hint: `${localPath}` },
    ],
  })
  if (p.isCancel(configChoice)) { p.cancel("Setup cancelled."); process.exit(0) }

  const configPath = configChoice === "global" ? globalPath : localPath

  // 5. Save config
  s.start("Saving config...")
  try {
    saveConfig(configPath, vault)
    s.stop(`Config saved`)
  } catch (err) {
    s.stop("Failed to save config")
    console.error(err)
    process.exit(1)
  }

  // 6. Init wiki structure
  s.start("Initializing wiki structure...")
  const results = [
    createWikiFile("schema/SCHEMA.md", SCHEMA_MD, vault),
    createWikiFile("wiki/INDEX.md", INDEX_MD, vault),
    createWikiFile("wiki/LOG.md", buildLogEntry(), vault),
    createWikiFile("raw/.keep", "", vault),
  ]
  const allOk = results.every(Boolean)
  if (allOk) {
    s.stop("Wiki structure initialized")
  } else {
    s.stop("Wiki structure partially created — run `obsidian_wiki_init` inside OpenCode to complete")
  }

  // 7. Done
  p.outro(
    `You're ready! Open OpenCode in any project and say:\n  "Add this article to my wiki: https://..."`
  )
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
