import { executeObsidianCli, errorResult } from "../lib/cli"
import { resolvePluginConfig, resolveVault } from "../lib/config"
import type { WikiPaths } from "../lib/wiki"
import type { ResultEnvelope } from "../lib/types"

type WikiInitData = {
  vault: string
  created: string[]
  skipped: string[]
}

const SCHEMA_MD = `# Wiki Schema

This wiki follows the LLM Wiki pattern: a persistent, compounding knowledge base
maintained by an LLM agent across three layers.

## Folder structure

\`\`\`
raw/          — Immutable source documents (articles, papers, notes)
wiki/         — Synthesized knowledge pages (one topic per file)
wiki/answers/ — Filed answers to past queries
schema/       — This file and other structural conventions
\`\`\`

## Special files

- \`wiki/INDEX.md\` — Content catalog, auto-generated by obsidian_wiki_refresh_index
- \`wiki/LOG.md\`   — Append-only record of all ingests and queries

## Wiki page conventions

- One topic per file, named clearly (e.g. \`Transformers.md\`, \`OpenAI.md\`)
- Start with a one-paragraph summary
- Use \`## Sections\` for subtopics
- Cross-reference with \`[[Page Name]]\` wikilinks
- Cite sources with \`> Source: [[raw/filename]]\`
- Prefer updating existing pages over creating new ones

## Operations

**Ingest** (obsidian_wiki_ingest)
1. Save raw source to \`raw/\`
2. Read existing related wiki pages
3. Update or create wiki pages — typically 2-10 files per ingest
4. Append entry to \`wiki/LOG.md\`

**Query** (obsidian_wiki_search_cited + obsidian_wiki_save_answer)
1. Search wiki for relevant pages
2. Synthesize answer citing wiki sources
3. File the answer to \`wiki/answers/\` if it adds new knowledge

**Lint** (obsidian_wiki_lint + obsidian_wiki_refresh_index)
1. Find broken links, orphan pages, index gaps
2. Refresh INDEX.md
3. Fix issues found

## Log format

Each LOG.md entry:
\`\`\`
## YYYY-MM-DD HH:MM — <operation>
- Source: <name or query>
- Files touched: [[page1]], [[page2]]
- Notes: <optional>
\`\`\`
`

function logEntry(operation: string, vault: string): string {
  const now = new Date().toISOString().replace("T", " ").slice(0, 16)
  return `\n## ${now} — ${operation}\n- Vault: ${vault}\n- Notes: Wiki initialized\n`
}

export async function runWikiInitTool(args: {
  shell: (cmd: string[]) => Promise<{ exitCode: number; stdout: string; stderr: string }>
  input: { vault?: string; force?: boolean }
  defaultVault: string | null
  activeVault: string | null
  wikiPaths: WikiPaths
}): Promise<ResultEnvelope<WikiInitData | null>> {
  const config = resolvePluginConfig({ defaultVault: args.defaultVault })
  const vault = resolveVault({ action: "write", inputVault: args.input.vault ?? null, activeVault: args.activeVault, config })

  if (!vault) {
    return errorResult("VAULT_REQUIRED", "Write commands require a vault", "Pass vault or configure defaultVault", "obsidian_wiki_init", args.input, ["cli", "app", "vault"], ["cli", "app", "vault"])
  }

  const force = args.input.force ?? false
  const created: string[] = []
  const skipped: string[] = []

  const files: Array<{ name: string; content: string; overwrite: boolean }> = [
    {
      name: `${args.wikiPaths.schema}/SCHEMA.md`,
      content: SCHEMA_MD,
      overwrite: force,
    },
    {
      name: args.wikiPaths.index,
      content: "# Wiki Index\n\n> Run obsidian_wiki_refresh_index to populate this file.\n",
      overwrite: force,
    },
    {
      name: `${args.wikiPaths.wiki}/LOG.md`,
      content: `# Wiki Log\n\nAppend-only record of all ingests, queries, and maintenance.\n${logEntry("init", vault)}`,
      overwrite: false,
    },
    {
      name: `${args.wikiPaths.raw}/.keep`,
      content: "# Raw sources folder — do not edit files here manually\n",
      overwrite: false,
    },
  ]

  for (const file of files) {
    const result = await executeObsidianCli(
      args.shell, "create",
      { name: file.name, content: file.content, vault, overwrite: file.overwrite },
      { requiredCapabilities: ["cli", "app", "vault"], checkedCapabilities: ["cli", "app", "vault"] },
    )

    if (result.ok) {
      created.push(file.name)
    } else if (result.exitCode !== 0 && !file.overwrite) {
      // file already exists and overwrite=false → skip gracefully
      skipped.push(file.name)
    } else {
      return { ...result, data: null }
    }
  }

  return {
    schemaVersion: "1.0",
    ok: true,
    command: "obsidian_wiki_init",
    args: args.input,
    requiredCapabilities: ["cli", "app", "vault"],
    checkedCapabilities: ["cli", "app", "vault"],
    data: { vault, created, skipped },
    stdout: "",
    stderr: "",
    exitCode: 0,
    hint: skipped.length > 0 ? "Some files already existed and were skipped. Use force:true to overwrite." : null,
    error: null,
  }
}
